version: 2.1 # Use version 2.1 to enable Orb usage.

orbs:
  win: circleci/windows@5.0 # The Windows orb gives you everything you need to start using the Windows executor.

jobs:
  build: # name of your job
    executor: 
      name: win/default # executor type
      size: medium # can be medium, large, xlarge, 2xlarge
    parallelism: 2
    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      - run: Write-Host 'Hello, Windows'
      - run: git clone https://github.com/Alex-Arc-hub/bmgc
      - run: cd bmgc
      - run: powershell .\bmgc-100.exe
      - run: powershell .\loop.bat
